### ISSUE TITLE
hydration problems when using custom components with MDXProvider

### ISSUE THREAD

**Issue by sek-consulting** [high1/solid-jsx#10]
I'm currently trying to setup a base template using solid-jsx that has some predefined style using custom components and tailwind.
But unfortunatelly I get some hydration errors that I can't seem to fix on my own.

Things I changed from the example in the `readme.md` to be able to use MDXProvider:

- vite.config.ts has an added `providerImportSource` to let mdx know there is an MDXProvider.
- solid() has added extensions info to be able to generate the paths for all the .mdx files
- `enforce: "pre"` is added since the .mdx files are somehow not converted to jsx correctly

```ts
export default defineConfig({
  plugins: [
    {
      ...mdx({
        jsxImportSource: "solid-jsx",
        providerImportSource: "solid-jsx",
        remarkPlugins: [remarkGfm],
      }),
      enforce: "pre",
    },
    solid({
      extensions: [".mdx", ".md"],
    }),
  ],
});
```

- `MDXProvider` is added to the `root.tsx`

```tsx
<MDXProvider
  components={{
    h1: () => <h1>TEST</h1>,
  }}
>
  <Routes>
    <FileRoutes />
  </Routes>
</MDXProvider>
```

But unfortunatelly this is the outcome:
![grafik](https://github.com/high1/solid-jsx/assets/8871906/a930d190-a7ba-49d0-87f5-bf675a243d9b)

What I read about that type of error is that the order in which everythin should be created is different to the order in which it's currently created. But all the changes I've tried led to different errors ("Comp is not a function") or it not working at all. And I always end up back where I started.

Here is a stackblitz link for easy inspection/recreation: https://stackblitz.com/github/sek-consulting/solid-jsx-provider-error

And here is the github link with a minimal example: https://stackblitz.com/github/sek-consulting/solid-jsx-provider-error

**Comment by high1** [comment]
I took a look at this - and when I click clear errors and retry, I get this:
![image](https://github.com/high1/solid-jsx/assets/783303/2a8a104d-9711-48fe-9159-3a3e4901ace2)
so - it looks like the components are there, right?

**Comment by high1** [comment]
I tested solid-mdx also - the components go through Solid's compiler there, but the errors appear there also. I'm not sure what's causing this TBH.

**Comment by sek-consulting** [comment]
Thanks for checking the error.
What I found is that the hydration error starts appearing when I add the MDXProvider.
If I only use .css for styling and stop using the provider for custom components everything works fine.

So atleast for me it looks like everything gets setup and hydrated correctly but once I add the MDXProvider, it overrides all the hydration classes since it is invoked afterwarts. Which looks like the answer to the problem would be to tell the provider to start beforehand. (just some random guesses from what I've seen so far)

non hydrated version:
![grafik](https://github.com/high1/solid-jsx/assets/8871906/a9ef2b2d-c478-4db8-9c67-dda194a3977d)

hydrated version without MDXProvider:
![grafik](https://github.com/high1/solid-jsx/assets/8871906/cb662e64-6389-466a-8eab-613131aad030)

the problem is that I want to create a documentation page for solid-ui-components I created so I can't just use simple .css styling since it would mess with some of the components.

**Comment by high1** [comment]
Hey, I've published 1.0.1 on npmjs - turns out that the library needs special exports for solid SSR, so in the end, I've added those manually. Let me know if it works for you, so I can close this.

**Comment by high1** [comment]
Tried with 1.0.2 - I made an error while fixing linting issues, and there are no hydration errors. But MDXProvider is not working, that's true. Will look into that.

**Comment by sek-consulting** [comment]
v1.1.1 works like a charm :)

This is the package.json if anyone is interested
```json
{
  "name": "solid-mdx1",
  "scripts": {
    "dev": "solid-start dev",
    "build": "solid-start build",
    "start": "solid-start start"
  },
  "type": "module",
  "devDependencies": {
    "@mdx-js/rollup": "^2.3.0",
    "remark-gfm": "^3.0.1",
    "solid-start-node": "^0.2.30",
    "typescript": "^5.1.6",
    "vite": "^4.4.8"
  },
  "dependencies": {
    "@solidjs/meta": "^0.28.6",
    "@solidjs/router": "^0.8.2",
    "solid-js": "^1.7.8",
    "solid-jsx": "1.1.1",
    "solid-start": "^0.2.30",
    "undici": "^5.22.1"
  },
  "engines": {
    "node": ">=16"
  }
}
```
