### ISSUE TITLE
Provide an MdxProvider

### ISSUE THREAD

**Issue by Zachiah** [high1/solid-jsx#2]
I need an MdxProvider (https://mdxjs.com/docs/using-mdx/#mdx-provider) like in the react or vue version.

**Comment by Zachiah** [comment]
It is basically a necessity for use with solid-start pages and custom components

**Comment by high1** [comment]
solid-jsx is a jsxImportSource, didn't have the intention to make it an mdx-provider also. I understand the use case, though, and may think about it.

**Comment by high1** [comment]
Added the MDXProvider implementation in 7c387af19c751a61aed6e164eb299c54100d823f.
