### ISSUE TITLE
Get `ReferenceError: navigator is not defined` error

### ISSUE THREAD

**Issue by nikitavoloboev** [high1/solid-jsx#4]
Trying to use this library with https://github.com/solidjs/solid-start

I get this error:

<img width="728" alt="image" src="https://user-images.githubusercontent.com/6391776/169669898-62b23657-fec8-4389-ac9b-b0457d2b599c.png">

```
ReferenceError: navigator is not defined
    at b (file:///Users/nikiv/src/personal/home-solid/node_modules/.pnpm/solid-jsx@0.7.1/node_modules/solid-jsx/dist/jsx-runtime.js:1:528)
    at file:///Users/nikiv/src/personal/home-solid/node_modules/.pnpm/solid-jsx@0.7.1/node_modules/solid-jsx/dist/jsx-runtime.js:1:8068
    at Array.map (<anonymous>)
    at file:///Users/nikiv/src/personal/home-solid/node_modules/.pnpm/solid-jsx@0.7.1/node_modules/solid-jsx/dist/jsx-runtime.js:1:8055
    at Array.map (<anonymous>)
    at file:///Users/nikiv/src/personal/home-solid/node_modules/.pnpm/solid-jsx@0.7.1/node_modules/solid-jsx/dist/jsx-runtime.js:1:8030
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
```

This is my `vite.config.js`: 

```
import mdx from "@mdx-js/rollup"
import remarkGfm from "remark-gfm"
import solid from "solid-start"
import { defineConfig } from "vite"

export default defineConfig({
  plugins: [
    mdx({ jsxImportSource: "solid-jsx", remarkPlugins: [remarkGfm] }),
    solid(),
  ],
  build: {
    target: "esnext",
  },
})
```

And here is me trying to use the mdx file (`index.mdx`) with this content.

```
---
type: page
title: About
date: 2022-01-01
description: Nikita's About page
---

Hey there.
```

Used:

<img width="658" alt="image" src="https://user-images.githubusercontent.com/6391776/169669949-6fd072a1-27dd-467b-b42f-c2c4e1d17c7e.png">

I think the solution is to wrap this line:

https://github.com/high1/solid-jsx/blob/4b17d5c25b2eca30351c2ac1dfd49788aa5a8fd3/src/utilities.ts#L6

With `isClient` from https://github.com/solidjs-community/solid-primitives

Because Solid Start apparently runs some Solid code on the server.

**Comment by high1** [comment]
Sorry for the late response, can you share some minimal code, since I'm not too familiar with solid-start?
